### ISSUE TITLE
Possible missing CSS

### ISSUE THREAD

**Issue by dsXLII** [jeherve/advanced-settings-for-jetpack#1]
I think the screenshot summarizes this one pretty well. :) The Jetpack logo, and the Automattic logo at the bottom, are not being scaled-down properly. Jetpack 4.9, WordPress 4.7.4.

![missing](https://cloud.githubusercontent.com/assets/10730424/26080651/315f6956-398d-11e7-89e6-a7c0f9597fce.png)

**Comment by jeherve** [comment]
This might be an issue with Jetpack itself, since my plugin doesn't control the display of the page, it only adds the menu item. What happens when you deactivate my plugin?

**Comment by dsXLII** [comment]
Without the plugin active, the screen looks somewhat more normal. :) 

![normal252](https://cloud.githubusercontent.com/assets/10730424/26122853/81900ba4-3a3e-11e7-98ad-6dbedff13d96.PNG)

**Comment by dsXLII** [comment]
Note that, in both cases, Jetpack is being modified by an in-house plugin, that disables some of Jetpack's features. (Just in case you look at the screenshots and notice about 2/3 of the modules aren't listed...) Unfortunately, if I deactivate that plugin (which also enforces dev mode), I can't even get to that screen, since the module list isn't available until after Jetpack is connected to wordpress.com in that instance.

All I'm doing is setting the dev mode constant, and removing a few items from the modules array, neither of which seem likely to affect rendering. I'll try to set up an internal dev site to confirm, though.

**Comment by jeherve** [comment]
Thanks for the extra details! Could you try to update? This should now be fixed, as per 8a192b39fa12ba273bd41d55c62cf903a4f71adc
